### ISSUE TITLE
kubepug doesn't find deprecated batch/v1beta1 CronJob API

### ISSUE THREAD

**Issue by peterjanes** [rikatz/kubepug#225]
`kubepug -k8s-version v1.21.0 --input-file deprecated-cronjob.yaml --error-on-deleted --error-on-deprecated` passes for this file (using `v1.21.0`, `v1.22.0`, and `v1.23.0`) but when deploying it to a v1.21.0 cluster I get the warning `Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob`.

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: foo
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: foo
            image: ...
          restartPolicy: Never
  schedule: 0 0 0 0 0
```
