### ISSUE TITLE
EKS cluster authentication issue

### ISSUE THREAD

**Issue by s2504s** [rikatz/kubepug#339]
### Error:
```
kubepug
time="2023-01-19T13:05:07+02:00" level=fatal msg="Failed communicating with k8s while discovering the object preferred name and gv. Error: Get \"https://7D44444444444444444444.sk2.us-west-1.eks.amazonaws.com/api?timeout=32s\": getting credentials: decoding stdout: no kind \"ExecCredential\" is registered for version \"client.authentication.k8s.io/v1alpha1\" in scheme \"pkg/runtime/scheme.go:100\""
```

### How to reproduce:
In order to reproduce this issue - create a kubeconfig file:
```
cat kube.conf

apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: https://7D44444444444444444444.sk2.us-west-1.eks.amazonaws.com
    certificate-authority-data: 
  name: my.cluster

contexts:
- context:
    cluster: my.cluster
    user: my.cluster
  name: my.cluster

current-context: my.cluster

users:
- name: my.cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "my-cluster"
        - "--profile"
        - "my-profile"
```
and run the app

#### Windows Versions:
kubepug.exe: Shows all the deprecated objects in a Kubernetes cluster allowing the operator to verify them before upgrading the cluster.
It uses the swagger.json version available in master branch of Kubernetes repository (github.com/kubernetes/kubernetes) as a reference.

GitVersion:    v1.4.0
GitCommit:     4de32d695b27c52c16d4a801b613b78e45e28ca9
GitTreeState:  clean
BuildDate:     2022-08-21T18:25:40
GoVersion:     go1.18.5
Compiler:      gc
Platform:      windows/amd64

#### Linux Versions:
kubepug: Shows all the deprecated objects in a Kubernetes cluster allowing the operator to verify them before upgrading the cluster.
It uses the swagger.json version available in master branch of Kubernetes repository (github.com/kubernetes/kubernetes) as a reference.

GitVersion:    v1.4.0
GitCommit:     4de32d695b27c52c16d4a801b613b78e45e28ca9
GitTreeState:  clean
BuildDate:     2022-08-21T18:25:40
GoVersion:     go1.18.5
Compiler:      gc
Platform:      linux/amd64
